package br.com.ares.identity.domain.model;

public enum Permission {
    CUSTOMER_READ,
    CUSTOMER_CREATE,
    CUSTOMER_UPDATE,
    CUSTOMER_DELETE,
    ASSET_READ,
    ASSET_CREATE,
    ASSET_UPDATE,
    ASSET_DELETE,
    SERVICE_READ,
    SERVICE_CREATE,
    SERVICE_UPDATE,
    SERVICE_DELETE,
    SERVICE_ORDER_READ,
    SERVICE_ORDER_CREATE,
    SERVICE_ORDER_UPDATE,
    SERVICE_ORDER_CANCEL,
    PAYMENT_READ,
    PAYMENT_CREATE,
    REPORT_READ,
    USER_MANAGE,
    TENANT_CONFIGURE
}
